format_version: 10
pipelines:
  jenkins_jobs:
    group: Tools
    materials:
      git-f14e4aa:
        git: https://github.com/chinnak7416/tools-automation-code.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      vault_token: AES:ygJYZCYQl2/+ct0sz1iW0w==:xIVBUeUEwQmqvq2zQNIsdFXXCB6tGiE4J8bJdp7mjms=
    stages:
      - Ansible:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible:
              tasks:
                - exec: { command: ansible-playbook,arguments: ["-i","jenkins-internal.ramdevops78.online,",  "tools.yml", "-e", "tool_name=jenkins", "-e", "ansible_user=ec2-user", "-e", "ansible_password=DevOps321", "-e", "jenkins_jobs=true"], run_if: passed}

