- name: Install jenkins-python
  ansible.builtin.pip:
    name: python-jenkins
  executable: pip3.9

- name: Copy  Job xml file
  ansible.builtin.template:
    src: jobs/pipeline.xml
    dest: /tmp/{{item}}.xml

- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/{{item}}.xml') }}"
    name: test
    password: "{{secrets.jenkins_password}}"
    url: http://jenkins-internal.ramdevops78.online:8080
    user: "{{secrets.jenkins_user}}"