- name: Set-prompt name
  ansible.builtin.shell: set-prompt jenkins

- name: Copy Jenkins repo
  ansible.builtin.template:
    src: jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Install Java & Jenkins
  ansible.builtin.dnf:
    name:
      - java-17-openjdk
      - fontconfig
      - jenkins
    state: installed

#- name: Create Init Directory
#  ansible.builtin.file:
#    path: /var/lib/jenkins/init.groovy.d
#    state: directory
#
#- name: Copy Init Scripts
#  ansible.builtin.template:
#    src: "{{item}}.groovy"
#    dest: /var/lib/jenkins/init.groovy.d/{{item}}.groovy
#  loop:
#    - 01-wizard
#    - 02-admin-user
#    - 03-plugins

- name: Start Jenkins
  ansible.builtin.systemd_service:
    name: jenkins
    state: restarted
    enabled: yes