- name: Set-prompt name
  ansible.builtin.shell: set-prompt jenkins

- name: Copy Jenkins repo
  ansible.builtin.template:
    src: jenkins.repo
    dest: /etc/jenkins/jenkins.repo

- name: Install Java & Jenkins
  ansible.builtin.dnf:
    name:
      - java-17-openjdk
      - fontconfig
      - jenkins
    state: installed

- name: Start Jenkins
  ansible.builtin.systemd_service:
    name: jenkins
    state: restarted
    enabled: yes